-- Copy and calculate this in Supabase SQL Editor

create table quotes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Project Details
  project_name text default 'Sin nombre',
  volume int,
  
  -- Specs
  length_cm numeric,
  width_cm numeric,
  height_cm numeric,
  material_type text, -- 'A' or 'B'
  
  -- Costs & Prices (Snapshots)
  material_unit_cost numeric,
  fab_cost numeric,
  mkt_cost numeric,
  
  margin_percent numeric,
  
  -- Results
  final_unit_price numeric,
  unif_profit numeric,
  total_project_profit numeric
);
